FIND_PACKAGE_HELPER(WbClient graphictypes.h)

IF(WBCLIENT_FOUND)
  SET(WBCLIENT_INCLUDE_DIRS ${WBCLIENT_INCLUDE_DIRS} ${WBCLIENT_INCLUDE_DIR}/TableauBlanc ${WBCLIENT_INCLUDE_DIR}/TableauBlanc/Messages ${WBCLIENT_INCLUDE_DIR}/TableauBlanc/Objets ${WBCLIENT_INCLUDE_DIR}/TableauBlanc/Socket)

  FIND_PACKAGE(Neolib REQUIRED)
  SET(WBCLIENT_INCLUDE_DIRS ${WBCLIENT_INCLUDE_DIRS} ${NEOLIB_INCLUDE_DIRS})
  SET(WBCLIENT_LIBRARIES ${WBCLIENT_LIBRARIES} ${NEOLIB_LIBRARIES})
  SET(WBCLIENT_DEFINITIONS ${NEOLIB_DEFINITIONS})
ENDIF(WBCLIENT_FOUND)

