FIND_PACKAGE_HELPER(GCLib GCSystem.h gclib gclibd)

IF(GCLIB_FOUND)
  IF(WIN32)
    SET(Boost_USE_STATIC_LIBS ON)
    SET(Boost_USE_MULTITHREADED ON)
    SET(Boost_USE_STATIC_RUNTIME OFF)
  ENDIF(WIN32)

  FIND_PACKAGE(Boost 1.42 COMPONENTS chrono system)

  SET(GCLIB_INCLUDE_DIRS ${GCLIB_INCLUDE_DIR} ${Boost_INCLUDE_DIRS})
  SET(GCLIB_LIBRARIES ${GCLIB_LIBRARIES} ${Boost_LIBRARIES})
ENDIF(GCLIB_FOUND)
