FIND_PACKAGE_HELPER(Cairo cairo.h QUIET)

IF(CAIRO_FOUND)
  IF(EXISTS ${CAIRO_INCLUDE_DIR}/cairo-version.h)
    # Recent versions such as 1.10.2
    PARSE_VERSION_OTHER(${CAIRO_INCLUDE_DIR}/cairo-version.h CAIRO_VERSION_MAJOR CAIRO_VERSION_MINOR CAIRO_VERSION_MICRO)
  ELSEIF(EXISTS ${CAIRO_INCLUDE_DIR}/cairo-features.h)
    # Old versions such as 1.6.4
    PARSE_VERSION_OTHER(${CAIRO_INCLUDE_DIR}/cairo-features.h CAIRO_VERSION_MAJOR CAIRO_VERSION_MINOR CAIRO_VERSION_MICRO)
  ELSE(EXISTS ${CAIRO_INCLUDE_DIR}/cairo-version.h)
    # Very old versions
    SET(CAIRO_VERSION_MAJOR 0)
    SET(CAIRO_VERSION_MINOR 0)
    SET(CAIRO_VERSION_MICRO 0)
  ENDIF(EXISTS ${CAIRO_INCLUDE_DIR}/cairo-version.h)
  
  SET(CAIRO_VERSION "${CAIRO_VERSION_MAJOR}.${CAIRO_VERSION_MINOR}.${CAIRO_VERSION_MICRO}")

  MESSAGE_VERSION_PACKAGE_HELPER(Cairo ${CAIRO_VERSION} ${CAIRO_LIBRARIES})
ENDIF(CAIRO_FOUND)
