FIND_PACKAGE_HELPER(Freeimage FreeImage.h QUIET)

IF(FREEIMAGE_FOUND)
  PARSE_VERSION_OTHER(${FREEIMAGE_INCLUDE_DIR}/png.h FREEIMAGE_MAJOR_VERSION FREEIMAGE_MINOR_VERSION FREEIMAGE_RELEASE_SERIAL)
  SET(FREEIMAGE_VERSION "${FREEIMAGE_MAJOR_VERSION}.${FREEIMAGE_MINOR_VERSION}.${FREEIMAGE_RELEASE_SERIAL}")

  MESSAGE_VERSION_PACKAGE_HELPER(Freeimage ${FREEIMAGE_VERSION} ${FREEIMAGE_LIBRARIES})
ENDIF(FREEIMAGE_FOUND)
