FIND_PACKAGE_HELPER(Bttp bttp.h)

IF(BTTP_FOUND)
  FIND_PACKAGE(MyBoost 1.42 COMPONENTS date_time system thread)

  IF(BOOST_FOUND)
    SET(BTTP_INCLUDE_DIRS ${BTTP_INCLUDE_DIRS} ${BOOST_INCLUDE_DIR})
    SET(BTTP_LIBRARIES ${BTTP_LIBRARIES} ${BOOST_LIBRARIES})
  ENDIF()
ENDIF(BTTP_FOUND)
