FIND_PACKAGE_HELPER(ZLIB zlib.h "z zlib zdll zlib1" "zlibd zdlld zlibd1" QUIET)

IF(ZLIB_INCLUDE_DIR AND EXISTS "${ZLIB_INCLUDE_DIR}/zlib.h")
  FILE(STRINGS "${ZLIB_INCLUDE_DIR}/zlib.h" ZLIB_H REGEX "^#define ZLIB_VERSION \"[^\"]*\"$")

  STRING(REGEX REPLACE "^.*ZLIB_VERSION \"([0-9]+).*$" "\\1" ZLIB_VERSION_MAJOR "${ZLIB_H}")
  STRING(REGEX REPLACE "^.*ZLIB_VERSION \"[0-9]+\\.([0-9]+).*$" "\\1" ZLIB_VERSION_MINOR  "${ZLIB_H}")
  STRING(REGEX REPLACE "^.*ZLIB_VERSION \"[0-9]+\\.[0-9]+\\.([0-9]+).*$" "\\1" ZLIB_VERSION_PATCH "${ZLIB_H}")
  SET(ZLIB_VERSION_STRING "${ZLIB_VERSION_MAJOR}.${ZLIB_VERSION_MINOR}.${ZLIB_VERSION_PATCH}")

  # only append a TWEAK version if it exists:
  SET(ZLIB_VERSION_TWEAK "")
  IF("${ZLIB_H}" MATCHES "^.*ZLIB_VERSION \"[0-9]+\\.[0-9]+\\.[0-9]+\\.([0-9]+).*$")
    SET(ZLIB_VERSION_TWEAK "${CMAKE_MATCH_1}")
    SET(ZLIB_VERSION_STRING "${ZLIB_VERSION_STRING}.${ZLIB_VERSION_TWEAK}")
  ENDIF("${ZLIB_H}" MATCHES "^.*ZLIB_VERSION \"[0-9]+\\.[0-9]+\\.[0-9]+\\.([0-9]+).*$")

  SET(ZLIB_MAJOR_VERSION "${ZLIB_VERSION_MAJOR}")
  SET(ZLIB_MINOR_VERSION "${ZLIB_VERSION_MINOR}")
  SET(ZLIB_PATCH_VERSION "${ZLIB_VERSION_PATCH}")

  MESSAGE_VERSION_PACKAGE_HELPER(ZLIB ${ZLIB_LIBRARIES} ${ZLIB_VERSION_STRING})
ENDIF(ZLIB_INCLUDE_DIR AND EXISTS "${ZLIB_INCLUDE_DIR}/zlib.h")
