FIND_PACKAGE(MyZLIB REQUIRED)

IF(ZLIB_FOUND)
  FIND_PACKAGE_HELPER(PNG png.h RELEASE libpng png15 libpng15 png14 libpng14 png12 libpng12 DEBUG libpngd png15d libpng15d png14d libpng14d png12d libpng12d QUIET)

  IF(PNG_FOUND)
    # png.h includes zlib.h. Sigh.
    SET(PNG_INCLUDE_DIRS ${PNG_PNG_INCLUDE_DIR} ${ZLIB_INCLUDE_DIR})
    SET(PNG_LIBRARIES ${PNG_LIBRARY} ${ZLIB_LIBRARIES})

    IF(CYGWIN)
      IF(BUILD_SHARED_LIBS)
        # No need to define PNG_USE_DLL here, because it's default for Cygwin.
      ELSE(BUILD_SHARED_LIBS)
        SET(PNG_DEFINITIONS -DPNG_STATIC)
      ENDIF(BUILD_SHARED_LIBS)
    ENDIF(CYGWIN)
  ENDIF(PNG_FOUND)

  PARSE_VERSION_OTHER(${PNG_INCLUDE_DIR}/png.h PNG_LIBPNG_VER_MAJOR PNG_LIBPNG_VER_MINOR PNG_LIBPNG_VER_RELEASE)
  SET(PNG_VERSION "${PNG_LIBPNG_VER_MAJOR}.${PNG_LIBPNG_VER_MINOR}.${PNG_LIBPNG_VER_RELEASE}")

  MESSAGE_VERSION_PACKAGE_HELPER(PNG ${PNG_VERSION} ${PNG_LIBRARIES})
ENDIF(ZLIB_FOUND)
