FOREACH(COMPONENT ${Poppler_FIND_COMPONENTS})
  IF(COMPONENT STREQUAL "poppler")
    FIND_PACKAGE_HELPER(Poppler poppler-config.h SUFFIXES poppler QUIET)
  ELSEIF(COMPONENT STREQUAL "poppler-cpp")
    FIND_PACKAGE_HELPER(PopplerCpp poppler-version.h RELEASE poppler-cpp DEBUG poppler-cppd SUFFIXES poppler/cpp QUIET)
  ELSEIF(COMPONENT STREQUAL "poppler-glib")
    FIND_PACKAGE_HELPER(PopplerGlib poppler.h RELEASE poppler-glib DEBUG poppler-glibd SUFFIXES poppler/glib QUIET)
  ELSEIF(COMPONENT STREQUAL "poppler-qt4")
    FIND_PACKAGE_HELPER(PopplerQt4 poppler-qt4.h RELEASE poppler-qt4 DEBUG poppler-qt4d SUFFIXES poppler/qt4 QUIET)
  ELSEIF(COMPONENT STREQUAL "poppler-qt5")
    FIND_PACKAGE_HELPER(PopplerQt5 poppler-qt5.h RELEASE poppler-qt5 DEBUG poppler-qt5d SUFFIXES poppler/qt5 QUIET)
  ENDIF(COMPONENT STREQUAL "poppler")
ENDFOREACH()

IF(POPPLER_FOUND)
  SET(POPPLER_INCLUDE_DIRS ${POPPLER_INCLUDE_DIRS} ${POPPLER_INCLUDE_DIR})

  PARSE_VERSION_OTHER(${POPPLER_INCLUDE_DIR}/poppler-config.h POPPLER_VERSION)

  IF(POPPLER_VERSION)
    PARSE_VERSION_STRING(${POPPLER_VERSION} POPPLER_VERSION_MAJOR POPPLER_VERSION_MINOR POPPLER_VERSION_PATCH)
  ELSE(POPPLER_VERSION)
    SET(POPPLER_VERSION_MAJOR 0)
    SET(POPPLER_VERSION_MINOR 10)
    SET(POPPLER_VERSION_PATCH 0)
    SET(POPPLER_VERSION "0.10.0")
  ENDIF(POPPLER_VERSION)

  CONVERT_VERSION_NUMBER(POPPLER_VERSION_NUM 100 ${POPPLER_VERSION_MAJOR} ${POPPLER_VERSION_MINOR} ${POPPLER_VERSION_PATCH})
  SET(POPPLER_DEFINITIONS "-DPOPPLER_VERSION_NUM=${POPPLER_VERSION_NUM}")

  MESSAGE_VERSION_PACKAGE_HELPER(Poppler ${POPPLER_VERSION} ${POPPLER_LIBRARIES})
ENDIF(POPPLER_FOUND)

IF(POPPLERGLIB_FOUND)
  SET(POPPLER_INCLUDE_DIRS ${POPPLER_INCLUDE_DIRS} ${POPPLERGLIB_INCLUDE_DIR})

  MESSAGE_VERSION_PACKAGE_HELPER(PopplerGlib ${POPPLER_VERSION} ${POPPLERGLIB_LIBRARIES})
ENDIF(POPPLERGLIB_FOUND)

IF(POPPLERQT4_FOUND)
  SET(POPPLER_INCLUDE_DIRS ${POPPLER_INCLUDE_DIRS} ${POPPLERQT4_INCLUDE_DIR})

  MESSAGE_VERSION_PACKAGE_HELPER(PopplerQt4 ${POPPLER_VERSION} ${POPPLERQT4_LIBRARIES})
ENDIF(POPPLERQT4_FOUND)

IF(POPPLERQT5_FOUND)
  SET(POPPLER_INCLUDE_DIRS ${POPPLER_INCLUDE_DIRS} ${POPPLERQT5_INCLUDE_DIR})

  MESSAGE_VERSION_PACKAGE_HELPER(PopplerQt5 ${POPPLER_VERSION} ${POPPLERQT5_LIBRARIES})
ENDIF(POPPLERQT5_FOUND)
