FIND_PACKAGE_HELPER(Luabind luabind/luabind.hpp)

IF(LUABIND_FOUND)
  FIND_PACKAGE(MyBoost REQUIRED)

  SET(LUABIND_INCLUDE_DIR ${LUABIND_INCLUDE_DIR} ${BOOST_INCLUDE_DIR})
  # Check if luabind/version.hpp exists
  FIND_FILE(LUABIND_VERSION_FILE luabind/version.hpp PATHS ${LUABIND_INCLUDE_DIR})
  IF(LUABIND_VERSION_FILE)
    SET(LUABIND_DEFINITIONS "-DHAVE_LUABIND_VERSION")
  ENDIF(LUABIND_VERSION_FILE)
ENDIF(LUABIND_FOUND)
