SET(NEL_LIBRARIES)
SET(NEL_INCLUDE_DIRS)

FOREACH(COMPONENT ${NeL_FIND_COMPONENTS})
  SET(_NAME NeL${COMPONENT})
  STRING(TOUPPER ${_NAME} _UPNAME)

  SET(${_NAME}_FIND_REQUIRED ${NeL_FIND_REQUIRED})

  FIND_PACKAGE_HELPER(${_NAME} nel/misc/types_nl.h
    RELEASE nel${COMPONENT}_r nel${COMPONENT}
    DEBUG nel${COMPONENT}_d
    QUIET)

  IF(${_UPNAME}_FOUND)
    LIST(APPEND NEL_LIBRARIES ${${_UPNAME}_LIBRARIES})
    IF(NOT NEL_INCLUDE_DIRS)
      SET(NEL_INCLUDE_DIRS ${${_UPNAME}_INCLUDE_DIRS})
    ENDIF()
  ENDIF(${_UPNAME}_FOUND)

  IF(COMPONENT STREQUAL "3d")
    FIND_PACKAGE(Freetype REQUIRED)
    LIST(APPEND NEL_LIBRARIES ${FREETYPE_LIBRARIES})
  ELSEIF(COMPONENT STREQUAL "misc")
    FIND_PACKAGE(MyPNG REQUIRED)
    FIND_PACKAGE(Jpeg REQUIRED)
    FIND_PACKAGE(LibXml2 REQUIRED)
    LIST(APPEND NEL_LIBRARIES ${PNG_LIBRARIES} ${JPEG_LIBRARIES} ${LIBXML2_LIBRARIES})
  ENDIF()
ENDFOREACH()

MESSAGE_VERSION_PACKAGE_HELPER(NeL "0.50" ${NEL_LIBRARIES})
