FIND_PACKAGE_HELPER(WbClient graphictypes.h wbclient wbclientd)

IF(WBCLIENT_FOUND)
  SET(WBCLIENT_INCLUDE_DIRS ${WBCLIENT_INCLUDE_DIRS} ${WBCLIENT_INCLUDE_DIR}/TableauBlanc ${WBCLIENT_INCLUDE_DIR}/TableauBlanc/Messages ${WBCLIENT_INCLUDE_DIR}/TableauBlanc/Objets ${WBCLIENT_INCLUDE_DIR}/TableauBlanc/Socket)
ENDIF(WBCLIENT_FOUND)

