SET(BTOLINKCONTROL_DIR ${BTOLINK_CONTROL_DIR})

IF(MFC_FOUND)
  SET(LIBRARY_RELEASE BtoLinkControlManager_win32)
  SET(LIBRARY_DEBUG BtoLinkControlManager_win32d)
ELSE(MFC_FOUND)
  SET(LIBRARY_RELEASE BtoLinkControlManager_qt)
  SET(LIBRARY_DEBUG BtoLinkControlManager_qtd)
ENDIF(MFC_FOUND)

FIND_PACKAGE_HELPER(BtoLinkControl btolinkmanager.h RELEASE ${LIBRARY_RELEASE} DEBUG ${LIBRARY_DEBUG})

IF(BTOLINKCONTROL_FOUND)
  FIND_PACKAGE(TinyXml REQUIRED)
  FIND_PACKAGE(MyBoost 1.42 COMPONENTS date_time system thread REQUIRED)

  SET(BTOLINKCONTROL_INCLUDE_DIRS ${BTOLINKCONTROL_INCLUDE_DIRS} ${BOOST_INCLUDE_DIRS})
  SET(BTOLINKCONTROL_LIBRARIES ${BTOLINKCONTROL_LIBRARIES} ${BOOST_LIBRARIES} ${TINYXML_LIBRARIES})
ENDIF(BTOLINKCONTROL_FOUND)
