FIND_PACKAGE_HELPER(Vorbis vorbisenc.h vorbis vorbisd)
FIND_PACKAGE_HELPER(VorbisFile vorbisfile.h vorbisfile vorbisfiled vorbis)

IF(VORBISFILE_FOUND)
  SET(VORBIS_LIBRARIES ${VORBIS_LIBRARIES} ${VORBISFILE_LIBRARIES})
ENDIF(VORBISFILE_FOUND)
