FIND_PACKAGE_HELPER(FontConfig fontconfig/fontconfig.h QUIET)

IF(FONTCONFIG_FOUND)
  PARSE_VERSION_OTHER(${FONTCONFIG_INCLUDE_DIR}/fontconfig/fontconfig.h FC_MAJOR FC_MINOR FC_REVISION)

  SET(FONTCONFIG_VERSION "${FC_MAJOR}.${FC_MINOR}.${FC_REVISION}")

  MESSAGE_VERSION_PACKAGE_HELPER(FontConfig ${FONTCONFIG_VERSION} ${FONTCONFIG_LIBRARIES})
ENDIF(FONTCONFIG_FOUND)
