FIND_PACKAGE_HELPER(TinyXml tinyxml.h RELEASE tinyxmlstl DEBUG tinyxmlstld QUIET)

IF(TINYXML_FOUND)
  SET(TINYXML_DEFINITIONS "-DTIXML_USE_STL")

  PARSE_VERSION_OTHER(${TINYXML_INCLUDE_DIR}/tinyxml.h TIXML_MAJOR_VERSION TIXML_MINOR_VERSION TIXML_PATCH_VERSION)
  SET(TINYXML_VERSION "${TIXML_MAJOR_VERSION}.${TIXML_MINOR_VERSION}.${TIXML_PATCH_VERSION}")

  MESSAGE_VERSION_PACKAGE_HELPER(TinyXml ${TINYXML_VERSION} ${TINYXML_LIBRARIES})
ENDIF(TINYXML_FOUND)
