FIND_PACKAGE_HELPER(Xvid xvid.h RELEASE xvidcore DEBUG xvidcored QUIET)

IF(XVID_FOUND)
  FILE(STRINGS ${XVID_INCLUDE_DIR}/xvid.h _FILE REGEX "#define XVID_VERSION    ")

  STRING(REGEX REPLACE "^.*XVID_MAKE_VERSION\\(([0-9,-]+)\\).*$" "\\1" XVID_VERSION "${_FILE}")
  STRING(REPLACE "," "." XVID_VERSION "${XVID_VERSION}")

  PARSE_VERSION_STRING(${XVID_VERSION} XVID_VERSION_MAJOR XVID_VERSION_MINOR)

  SET(XVID_VERSION "${XVID_VERSION_MAJOR}.${XVID_VERSION_MINOR}")

  MESSAGE_VERSION_PACKAGE_HELPER(Xvid ${XVID_VERSION} ${XVID_LIBRARIES})
ENDIF()
