FIND_PACKAGE_HELPER(Neolib NeoLib.h neolib neolibd)

IF(NEOLIB_FOUND)
  SET(NEOLIB_DEFINITIONS "-DSERIALISATION_USE_BOOST_SHARED")

  IF(WIN32)
    SET(Boost_USE_STATIC_LIBS ON)
    SET(Boost_USE_MULTITHREADED ON)
    SET(Boost_USE_STATIC_RUNTIME OFF)
  ENDIF(WIN32)

  FIND_PACKAGE(Boost 1.42 COMPONENTS date_time filesystem system thread)

  # TODO: add to NEOLIB_INCLUDE_DIRS
  INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS})
  LINK_DIRECTORIES(${Boost_LIBRARY_DIRS})
ENDIF(NEOLIB_FOUND)
