FIND_PACKAGE_HELPER(GCLib GCSystem.h)

IF(GCLIB_FOUND)
  FIND_PACKAGE(Neolib)
  
  IF(NEOLIB_FOUND)
    SET(GCLIB_INCLUDE_DIRS ${GCLIB_INCLUDE_DIRS} ${NEOLIB_INCLUDE_DIRS})
    SET(GCLIB_LIBRARIES ${GCLIB_LIBRARIES} ${NEOLIB_LIBRARIES})
  ENDIF(NEOLIB_FOUND)

  FIND_PACKAGE(Boost 1.42 COMPONENTS chrono system)

  SET(GCLIB_INCLUDE_DIRS ${GCLIB_INCLUDE_DIRS} ${Boost_INCLUDE_DIRS})
  SET(GCLIB_LIBRARIES ${GCLIB_LIBRARIES} ${Boost_LIBRARIES})

  SET(GCLIB_DEFINITIONS ${NEOLIB_DEFINITIONS})
ENDIF(GCLIB_FOUND)
