FIND_PACKAGE_HELPER(ZLIB zlib.h RELEASE z zlib zdll zlib1 DEBUG zlibd zdlld zlibd1 QUIET)

IF(ZLIB_INCLUDE_DIR AND EXISTS "${ZLIB_INCLUDE_DIR}/zlib.h")
  PARSE_VERSION_OTHER(${ZLIB_INCLUDE_DIR}/zlib.h ZLIB_VERSION ZLIB_VER_MAJOR ZLIB_VER_MINOR ZLIB_VER_REVISION ZLIB_VER_SUBREVISION)

  IF(NOT ZLIB_VER_MAJOR)
    STRING(REGEX REPLACE "^([0-9]+).*$" "\\1" ZLIB_VERSION_MAJOR "${ZLIB_VERSION}")
    STRING(REGEX REPLACE "^[0-9]+\\.([0-9]+).*$" "\\1" ZLIB_VERSION_MINOR  "${ZLIB_VERSION}")
    STRING(REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+).*$" "\\1" ZLIB_VERSION_PATCH "${ZLIB_VERSION}")
  ENDIF(NOT ZLIB_VER_MAJOR)
  
  MESSAGE_VERSION_PACKAGE_HELPER(ZLIB ${ZLIB_VERSION} ${ZLIB_LIBRARIES})
ENDIF(ZLIB_INCLUDE_DIR AND EXISTS "${ZLIB_INCLUDE_DIR}/zlib.h")
