IF(RFB_LIB_DIR)
  SET(RFBLIB_DIR ${RFB_LIB_DIR})
ENDIF(RFB_LIB_DIR)

FIND_PACKAGE_HELPER(RfbLib RfbLib.h)

IF(RFBLIB_FOUND)
  FIND_PACKAGE(OpenSSL REQUIRED)
  FIND_PACKAGE(Neolib REQUIRED)
  FIND_PACKAGE(ZLIB REQUIRED)
  FIND_PACKAGE(JPEG REQUIRED)

  SET(RFBLIB_INCLUDE_DIRS ${RFBLIB_INCLUDE_DIR} ${OPENSSL_INCLUDE_DIR} ${NEOLIB_INCLUDE_DIR} ${ZLIB_INCLUDE_DIR} ${JPEG_INCLUDE_DIR})
  SET(RFBLIB_LIBRARIES ${RFBLIB_LIBRARIES} ${OPENSSL_LIBRARIES} ${NEOLIB_LIBRARIES} ${ZLIB_LIBRARY} ${JPEG_LIBRARY})
  SET(RFBLIB_DEFINITIONS ${NEOLIB_DEFINITIONS})

  IF(WIN32)
    SET(RFBLIB_LIBRARIES ${RFBLIB_LIBRARIES} Ws2_32)
  ENDIF(WIN32)
ENDIF(RFBLIB_FOUND)
