FIND_PACKAGE_HELPER(DevIL IL/il.h RELEASE IL DEBUG ILd QUIET)

IF(DEVIL_FOUND)
  SET(DEVIL_DEFINITIONS "-DHAVE_DEVIL")

  IF(WIN32)
    SET(DEVIL_DEFINITIONS "${DEVIL_DEFINITIONS} -DIL_STATIC_LIB")
  ENDIF(WIN32)

  PARSE_VERSION_OTHER(${DEVIL_INCLUDE_DIR}/IL/il.h IL_VERSION)

  IF(IL_VERSION)
    STRING(SUBSTRING ${IL_VERSION} 0 1 DEVIL_VERSION_MAJOR)
    STRING(SUBSTRING ${IL_VERSION} 1 1 DEVIL_VERSION_MINOR)
    STRING(SUBSTRING ${IL_VERSION} 2 1 DEVIL_VERSION_PATCH)
  ENDIF(IL_VERSION)

  SET(DEVIL_VERSION "${DEVIL_VERSION_MAJOR}.${DEVIL_VERSION_MINOR}.${DEVIL_VERSION_PATCH}")

  MESSAGE_VERSION_PACKAGE_HELPER(DevIL ${DEVIL_VERSION} ${DEVIL_LIBRARIES})
ENDIF(DEVIL_FOUND)
