FIND_PACKAGE_HELPER(Neolib NeoLib.h QUIET)

IF(NEOLIB_FOUND)
  SET(NEOLIB_DEFINITIONS "-DSERIALISATION_USE_BOOST_SHARED")

  FIND_PACKAGE(MyBoost 1.42 COMPONENTS date_time filesystem system thread REQUIRED)

  IF(BOOST_FOUND)
    SET(NEOLIB_INCLUDE_DIRS ${NEOLIB_INCLUDE_DIRS} ${BOOST_INCLUDE_DIRS})
    SET(NEOLIB_LIBRARIES ${NEOLIB_LIBRARIES} ${BOOST_LIBRARIES})
  ENDIF()

  FIND_PACKAGE(OpenSSL REQUIRED)

  IF(OPENSSL_FOUND)
    SET(NEOLIB_INCLUDE_DIRS ${NEOLIB_INCLUDE_DIRS} ${OPENSSL_INCLUDE_DIR})
    SET(NEOLIB_LIBRARIES ${NEOLIB_LIBRARIES} ${OPENSSL_LIBRARIES})
  ENDIF(OPENSSL_FOUND)

  IF(WIN32)
    SET(NEOLIB_LIBRARIES ${NEOLIB_LIBRARIES} Ws2_32)
  ENDIF(WIN32)

  PARSE_VERSION_OTHER(${NEOLIB_INCLUDE_DIR}/neolib_version.h NEOLIB_VERSION_MAJOR NEOLIB_VERSION_MINOR NEOLIB_VERSION_PATCH)

  IF(NOT NEOLIB_VERSION_MAJOR)
    PARSE_VERSION_OTHER(${NEOLIB_INCLUDE_DIR}/NeoLib.h NEOLIB_VERSION_MAJOR NEOLIB_VERSION_MINOR NEOLIB_VERSION_PATCH)
  ENDIF(NOT NEOLIB_VERSION_MAJOR)

  SET(NEOLIB_VERSION "${NEOLIB_VERSION_MAJOR}.${NEOLIB_VERSION_MINOR}.${NEOLIB_VERSION_PATCH}")

  MESSAGE_VERSION_PACKAGE_HELPER(Neolib ${NEOLIB_VERSION} ${NEOLIB_LIBRARIES})
ENDIF(NEOLIB_FOUND)
