FIND_PACKAGE_HELPER(Vorbis vorbis.h vorbis vorbisd)
FIND_PACKAGE_HELPER(VorbisFile vorbisfile.h vorbisfile vorbisfiled)

IF(VORBISFILE_FOUND)
  SET(VORBIS_LIBRARIES ${VORBIS_LIBRARIES} ${VORBISFILE_LIBRARIES})
ENDIF(VORBISFILE_FOUND)
