FIND_PACKAGE_HELPER(FreeimagePlus FreeImagePlus.h QUIET)

IF(FREEIMAGEPLUS_FOUND)
  PARSE_VERSION_OTHER(${FREEIMAGEPLUS_INCLUDE_DIR}/FreeImage.h FREEIMAGE_MAJOR_VERSION FREEIMAGE_MINOR_VERSION FREEIMAGE_RELEASE_SERIAL)
  SET(FREEIMAGE_VERSION "${FREEIMAGE_MAJOR_VERSION}.${FREEIMAGE_MINOR_VERSION}.${FREEIMAGE_RELEASE_SERIAL}")

  MESSAGE_VERSION_PACKAGE_HELPER(FreeimagePlus ${FREEIMAGE_VERSION} ${FREEIMAGEPLUS_LIBRARIES})
ENDIF(FREEIMAGEPLUS_FOUND)
