FIND_PACKAGE_HELPER(Pqxx pqxx/pqxx RELEASE libpqxx DEBUG libpqxxD QUIET)

IF(PQXX_FOUND)
  SET(PQXX_DEFINITIONS "-DPQXX_SHARED")

  PARSE_VERSION_OTHER(${PQXX_INCLUDE_DIR}/pqxx/version.hxx PQXX_VERSION_MAJOR PQXX_VERSION_MINOR)

  SET(PQXX_VERSION "${PQXX_VERSION_MAJOR}.${PQXX_VERSION_MINOR}")

  MESSAGE_VERSION_PACKAGE_HELPER(Pqxx ${PQXX_VERSION} ${PQXX_LIBRARIES})
ENDIF(PQXX_FOUND)
