FIND_PACKAGE_HELPER(Pqxx pqxx/pqxx RELEASE libpqxx libpqxx_static DEBUG libpqxxD libpqxx_staticD QUIET)

IF(PQXX_FOUND)
  IF(PQXX_LIBRARY_RELEASE MATCHES "static")
    SET(PQXX_TYPE "static")

    # static version of pqxx needs libpq
    FIND_PACKAGE(Libpq REQUIRED)
    IF(LIBPQ_FOUND)
      LIST(APPEND PQXX_LIBRARIES ${LIBPQ_LIBRARIES})
    ENDIF()
  ELSE()
    SET(PQXX_TYPE "shared")
    SET(PQXX_DEFINITIONS "-DPQXX_SHARED")
  ENDIF()

  PARSE_VERSION_OTHER(${PQXX_INCLUDE_DIR}/pqxx/version.hxx PQXX_VERSION_MAJOR PQXX_VERSION_MINOR)

  # First version with pqxx_version.hxx is 3.1
  IF(NOT PQXX_VERSION_MAJOR)
    SET(PQXX_VERSION_MAJOR 2)
    SET(PQXX_VERSION_MINOR 0)
  ENDIF(NOT PQXX_VERSION_MAJOR)

  SET(PQXX_VERSION "${PQXX_VERSION_MAJOR}.${PQXX_VERSION_MINOR}")

  MESSAGE_VERSION_PACKAGE_HELPER(Pqxx "${PQXX_VERSION} ${PQXX_TYPE}" ${PQXX_LIBRARIES})
ENDIF(PQXX_FOUND)
