SET(BASECLASSES_DIR ${DSHOWSDK_DIR})
FIND_PACKAGE_HELPER(BaseClasses streams.h baseclasses baseclassesd)

IF(BASECLASSES_FOUND)
  SET(BASECLASSES_LIBRARIES Strmiids Winmm ${BASECLASSES_LIBRARIES})
ENDIF(BASECLASSES_FOUND)
