SET(LIBRARY_NAME_RELEASE cpptest)
SET(LIBRARY_NAME_DEBUG cpptestd)

IF(WITH_STLPORT)
  SET(LIBRARY_NAME_RELEASE cpptest_stlport ${LIBRARY_NAME_RELEASE})
  SET(LIBRARY_NAME_DEBUG cpptest_stlportd ${LIBRARY_NAME_DEBUG})
ENDIF(WITH_STLPORT)

FIND_PACKAGE_HELPER(Cairo cpptest.h ${LIBRARY_NAME_RELEASE} ${LIBRARY_NAME_DEBUG} cppunit)
