FIND_PACKAGE_HELPER(JRTPLIB rtpconfig.h jrtplib jrtplib_d "jrtplib3")

FIND_PACKAGE_HELPER(JThread jthread.h jthread jthread_d "jthread")

IF(JRTPLIB_FOUND)
  SET(JRTPLIB_INCLUDE_DIRS ${JRTPLIB_INCLUDE_DIR} ${JTHREAD_INCLUDE_DIR})
  SET(JRTPLIB_LIBRARIES ${JRTPLIB_LIBRARIES} ${JTHREAD_LIBRARIES})
ENDIF(JRTPLIB_FOUND)