FIND_PACKAGE_HELPER(DevIL IL/il.h IL ILd)

IF(DEVIL_FOUND)
  SET(DEVIL_DEFINITIONS "-DHAVE_DEVIL")
  IF(WIN32)
    SET(DEVIL_DEFINITIONS "${DEVIL_DEFINITIONS} -DIL_STATIC_LIB")
  ENDIF(WIN32)
ENDIF(DEVIL_FOUND)
