FIND_PACKAGE_HELPER(Bttp bttp.h)

IF(BTTP_FOUND)
  FIND_PACKAGE(Boost 1.42 COMPONENTS date_time system thread)

  IF(Boost_FOUND)
    SET(BTTP_INCLUDE_DIRS ${BTTP_INCLUDE_DIRS} ${Boost_INCLUDE_DIR})
    SET(BTTP_LIBRARIES ${BTTP_LIBRARIES} ${Boost_LIBRARIES})
  ENDIF(Boost_FOUND)
ENDIF(BTTP_FOUND)
