CMAKE_MINIMUM_REQUIRED(VERSION 2.6.3)

SET(CMAKE_MODULE_PATH "${SOURCE_DIR}/CMakeModules;${CMAKE_MODULE_PATH}")

IF(EXISTS "${SOURCE_DIR}/.svn/")
  FIND_PACKAGE(Subversion)

  IF(SUBVERSION_FOUND)
    Subversion_WC_INFO(${SOURCE_DIR} ER)
    SET(REVISION ${ER_WC_REVISION})
  ENDIF(SUBVERSION_FOUND)
ENDIF(EXISTS "${SOURCE_DIR}/.svn/")

IF(EXISTS "${SOURCE_DIR}/.hg/")
  FIND_PACKAGE(Mercurial)

  IF(MERCURIAL_FOUND)
    Mercurial_WC_INFO(${SOURCE_DIR} ER)
    SET(REVISION ${ER_WC_REVISION})
  ENDIF(MERCURIAL_FOUND)
ENDIF(EXISTS "${SOURCE_DIR}/.hg/")

IF(REVISION AND EXISTS ${SOURCE_DIR}/revision.h.in)
  CONFIGURE_FILE(${SOURCE_DIR}/revision.h.in revision.h.txt)
  EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E copy revision.h.txt revision.h) # copy_if_different
ENDIF(REVISION AND EXISTS ${SOURCE_DIR}/revision.h.in)
